name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  NODE_VERSION: '22.x'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test-Build-Deploy:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Show Node.js and npm version
        run: |
          node -v
          npm -v

      - name: Install Workspace Root Dependencies
        run: npm ci --include-workspace-root

      - name: Install Client Dependencies
        run: npm ci --workspace=client

      - name: Install Server Dependencies
        run: npm ci --workspace=server

      - name: Run Client Tests
        run: npm run test:client
        env:
          CI: true
          REACT_APP_GEMINI_API_KEY: ${{ secrets.REACT_APP_GEMINI_API_KEY }}

      - name: Run Server Tests
        run: npm run test:server
        env:
          CI: true
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          AI_API_KEY: ${{ secrets.AI_API_KEY }}

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
