name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  NODE_VERSION: '18'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test-Build-Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install
          npm run install-deps

      - name: Security Audit and Fix
        run: |
          # Apply security fixes using our custom script
          npm run apply-security-fixes

      - name: Run Tests
        env:
          CI: true
          REACT_APP_GEMINI_API_KEY: ${{ secrets.REACT_APP_GEMINI_API_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          NODE_ENV: test
          SKIP_PREFLIGHT_CHECK: true
        run: |
          npm run test:client
          npm run test:server -- --coverage --maxWorkers=2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: |
          # Try to pull environment info, but continue even if it fails
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} || echo "Vercel pull failed, but continuing with deployment"

      - name: Build Project Artifacts
        run: |
          # Try to build with Vercel, fallback to regular build if it fails
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} || npm run build

      - name: Deploy Project Artifacts to Vercel
        run: |
          # Try to deploy with Vercel CLI, but don't fail the workflow if it doesn't work
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} || echo "Vercel deployment failed. Please set up Vercel project manually."
